name: Build Linux Executable

on:
  workflow_dispatch: # This adds the manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker run --name build-container -v ${{ github.workspace }}:/workspace -w /workspace centos:7 bash -c "
          # Update the system and install necessary tools
          yum -y update && \
          yum groupinstall -y 'Development Tools' && \
          yum install -y centos-release-scl && \
          yum install -y wget && \
          
          # Install Developer Toolset (GCC 7)
          yum install -y devtoolset-7-gcc devtoolset-7-gcc-c++ devtoolset-7-binutils && \
          
          # Enable the Developer Toolset (GCC 7)
          scl enable devtoolset-7 bash && \
          
          # Install Node.js
          wget https://nodejs.org/dist/v20.13.1/node-v20.13.1-linux-x64.tar.xz && \
          tar -xJf node-v20.13.1-linux-x64.tar.xz -C /usr/local --strip-components=1 && \
          rm node-v20.13.1-linux-x64.tar.xz && \
          
          # Install Nexe globally
          npm install -g nexe && \
          
          # Install project dependencies
          if [ -f package-lock.json ]; then npm ci --force; else npm install --force; fi && \
          
          # Build the application using Nexe
          nexe thetvapp-win64.js -t linux-x64-20.13.1 -o thetvapp-linux --build
        "

    - name: Upload built executable
      uses: actions/upload-artifact@v2
      with:
        name: thetvapp-linux
        path: thetvapp-linux
