name: Run Playlist Script

on:
  schedule:
    - cron: '0 0 * * *'  # At 00:00 (midnight) UTC
    - cron: '0 12 * * *' # At 12:00 (noon) UTC
  workflow_dispatch: # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Specify your PHP version

    - name: Run PHP script
      run: php playlist/create_movie_playlist.php
      env:
        SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}

    - name: Commit and Push to Public Repository
      run: |
        git config user.name "gogetta69"
        git config user.email "gogetta.teams@gmail.com"
        git add playlist.m3u8 playlist.json
        git commit -m "Update Playlist" || echo "No changes to Playlist"
        git push https://x-access-token:${{ secrets.RUN_ACTIONS }}@github.com/gogetta69/public-files.git
