name: Run Playlist Script

on:
  schedule:
    - cron: '0 0 * * *'  # At 00:00 (midnight) UTC
    - cron: '0 12 * * *' # At 12:00 (noon) UTC
  workflow_dispatch: # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v4
      with:
        php-version: '7.4' # Specify your PHP version

    - name: Run PHP script
      run: php playlist/create_movie_playlist.php
      env:
        SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}

    - name: List files
      run: ls -l

    - name: Commit and Push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add playlist.m3u8 playlist.json
        git commit -m "Update playlist files" || echo "No changes to commit"
        git push https://${{ secrets.RUN_ACTIONS_KEY }}@github.com/gogetta69/public-files.git
