name: Merge EPG Data

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    
    - name: Run Pluto Data Script
      run: php php/grab_pluto_data.php
      continue-on-error: true

    - name: List Files in Pluto-TV Directory
      run: ls -l Pluto-TV

    - name: Add generated files to Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Pluto-TV/us.m3u8 Pluto-TV/us.xml
        git commit -m "Update Pluto TV EPG and playlist"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print Environment Variables
      run: printenv

    - name: Run PHP Script
      env:
        GAS_KEY: ${{ secrets.GAS_KEY }}
      run: php php/mergeEpgs.php

